[programs.devnet]
farm = "HGqZYyZuJfBs5sskdoBWcjRs6mCMCwDUQTYc3yK9mH6S"
bank = "ChNJdVCzoAxQM5u6d56M39jpwVxd77M31k9fnz9pFzhj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/solana/art_farm/.wallets/cm-authority/id-devnet.json"

[scripts]
test_mint = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts --keypair=./.wallets/person-minting/id-devnet.json"
init_farm = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializeFarm.ts --keypair=./.wallets/cm-authority/id-devnet.json"
init_collection = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/createCollection.ts --keypair=./.wallets/cm-authority/id-devnet.json"
