[programs.devnet]
nft_buoy = "7FU1DwsTzUheVH4rQBy4ZM89fMMDwJeS5wBVh1dpRVyC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/solana/nft_buoy/.wallets/cm-authority/id-devnet.json"

[scripts]
test_mint = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts --keypair=./.wallets/person-minting/id-devnet.json"
test_init_candy_machine = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializeCandyMachine.ts --keypair=./.wallets/cm-authority/id-devnet.json"
test_create_collection = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/createCollection.ts --keypair=./.wallets/cm-authority/id-devnet.json"
test_get_cm_state = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/getCandyMachineState.ts --keypair=./.wallets/person-minting/id-devnet.json"