[programs.devnet]
farm = "C1f5CTDEJ1ujVQoaB6ySCAXDWPS4BQnsRgCmW5KiQVRP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/solana/farm/.wallets/cm-authority/id-devnet.json"

[scripts]
test_mint = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts --keypair=./.wallets/person-minting/id-devnet.json"
init_farm = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializeFarm.ts --keypair=./.wallets/cm-authority/id-devnet.json"
init_collection = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/createCollection.ts --keypair=./.wallets/cm-authority/id-devnet.json"
