[programs.devnet]
farm = "BbNeEhJmVCyXHc28TvFowCJgZuTUsCszjcwMhQ7uxjQs"
bank = "8VWkHD4LHMtHz4Er1AVkGvAnJbtLYrbC13JCHNyvDDYL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/test/art_farm/devnet/payer.json"

[scripts]
test_mint = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts --keypair=/Users/mike/.config/solana/test/art_farm/devnet/testBuyer.json"
init_farm = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializeFarm.ts --keypair=/Users/mike/.config/solana/test/art_farm/devnet/farmAuthority.json"
init_collection = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/createCollection.ts --keypair=/Users/mike/.config/solana/test/art_farm/devnet/creator.json"
farm_acct_info = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/fetchFarmAcc.ts"
