[programs.devnet]
nft_buoy = "Ft9edb9hsAtDMCdwDQ8AxWM4PsudnnfjqjzNReZQ8DRo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/solana/nft_buoy/.wallets/cm-authority/id-devnet.json"

[scripts]
test_mint = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts --keypair=./.wallets/person-minting/id-devnet.json"
test_init_candy_machine = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/initializeCandyMachine.ts --keypair=./.wallets/cm-authority/id-devnet.json"
test_create_collection = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/createCollection.ts --keypair=./.wallets/cm-authority/id-devnet.json"